name: rehab_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Add your dependencies here:
  cupertino_icons:    ^1.0.8
  intl:               ^0.20.2
  light_sensor:       ^3.0.1
  permission_handler: ^11.4.0
  provider:           ^6.1.2
  sensors_plus:       ^6.1.1
  syncfusion_flutter_charts: ^28.2.6

# Developer dependencies are other packages that your package needs ONLY
# during development like for testing, code generation, or linting.
# They're not included in the actual app when it’s built for release.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:      ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/example/000_exercise.gif
    - assets/example/001_exercise.gif
    - assets/example/002_exercise.gif
    - assets/example/003_exercise.gif
    - assets/example/FEI_logo.gif
    - assets/eating_rehab/eating.png
    - assets/eating_rehab/eat_spoon.png
    - assets/eating_rehab/secure_phone.png
    - assets/eating_rehab/ok.png
    - assets/eating_rehab/start.png
    - assets/eating_rehab/stop.png
    - assets/eating_rehab/measure.gif
    - assets/eating_rehab/click.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
